import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  home: {
    backgroundColor: '#eeeeee',
  },
	banner: {
		backgroundColor: '#6c6c6c',
		paddingTop: 15,
		paddingBottom: 15,
		paddingLeft: 50,
		paddingRight: 50,
	},
	h1: {
		fontSize: 36,
		fontWeight: '700',
		color: '#fff',
		marginBottom: 10, 
	},
	h2: {
		fontSize: 22,
		fontWeight: '700',
		color: '#fff', 
		marginBottom: 10,
	},
	button: {
		backgroundColor: '#f62f5e',
		fontSize:18,
		fontWeight: '700',
		color: '#fff',
		borderRadius: 20,
		paddingTop: 15,
		paddingBottom: 15,
		paddingLeft: 30,
		paddingRight: 30,
		textAlign: 'center',
		width: 150,
	},
	shop_now_panel:{
		margin:15,
		marginBottom: 30,
		padding: 15,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
	},
	product_panel:{
		flex:1,
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'column',
	},
	sale:{
		backgroundColor: '#00d3ca',
		color:'#fff',
		paddingTop: 5,
		paddingBottom: 5,
		paddingLeft: 10,
		paddingRight: 10,
		width: 50,
		position: 'absolute',
		left: 0,
		top: 0,
		zIndex: 0,
		},
	shop_now: {
		textAlign: 'center',
		display:'flex',
		flex:1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	title1: {		
		color: '#2e2e2e', 
	},
	shoptxt: {
		marginBottom:10,
		textAlign:'center',
	},
	wow_block: {
		backgroundColor: '#00d3ca',
		padding: 10,
		margin: 15,
		marginBottom: 30, 
		minHeight: 345,
		flex:1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
	},
});