import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
   home: {
     backgroundColor: '#f7f7f7',
   },
   basefont:{
		fontSize: 16,
		fontWeight:'400',
	},
	gray_bg:{
		backgroundColor: '#f7f7f7',
	},
	banner: {
		backgroundColor: '#6c6c6c',
		paddingTop: 25,
		paddingBottom: 50,
		paddingLeft: 50,
		paddingRight: 50,
		flex:1,
		justifyContent: 'center',
		alignItems: 'flex-start',
	},
	img: {
		width: null,
		height: 300,
		flex:1,
	},
	h1: {
		fontSize: 36,
		fontWeight: '700',
		color: '#fff',
		marginBottom: 10,
	},
	h2: {
		fontSize: 22,
		fontWeight: '700',
		color: '#fff',
		marginBottom: 10,
	},
	h3: {
		fontSize: 16,
		fontWeight: '700',
		marginBottom: 10,
	},
	black: {
		color: '#2e2e2e',
	},
	red: {
		color: '#f62f5e',
	},
	white: {
		color: '#fff',
	},
	error:{
		color: '#f62f5e',
		marginTop:10,
		marginBottom:15,
	},
	button: {
		backgroundColor: '#f62f5e',
		fontSize:18,
		fontWeight: '700',
		color: '#fff',
		borderRadius: 20,
		paddingTop: 10,
		paddingBottom: 10,
		paddingLeft: 15,
		paddingRight: 15,
		textAlign: 'center',
		minWidth: 110,
	},
	shop_now_panel:{
		margin:15,
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
	},
	product_panel:{
		flex:1,
		alignItems: 'center',
		justifyContent: 'center',
		flexDirection: 'column',
	},
	sale:{
		backgroundColor: '#00d3ca',
		color:'#fff',
		paddingTop: 5,
		paddingBottom: 5,
		paddingLeft: 10,
		paddingRight: 10,
		width: 'auto',
		position: 'absolute',
		left: 0,
		top: 0,
		zIndex: 1,
		fontSize: 16,
		fontWeight: '400',
		},
	shop_now: {
		textAlign: 'center',
		display:'flex',
		flex:1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	shoptxt: {
		marginBottom:15,
		textAlign:'center',
		fontSize: 16,
		fontWeight: '400',
	},
  productdesc: {
		marginBottom:15,
		fontSize: 16,
		fontWeight: '400',
	},
	wow_block: {
		backgroundColor: '#00d3ca',
		padding: 15,
		margin: 15,
		marginBottom: 30,
		minHeight: 345,
		flex:1,
		flexDirection: 'column',
		alignItems: 'center',
		justifyContent: 'center',
	},
	game_begin_img_block: {
		marginLeft: 15,
		marginRight: 15,
		marginTop: 15,
	},
	game_sub_block: {
		marginLeft:15,
		marginRight: 15,
		marginTop: 0,
		marginBottom: 60,
		padding: 30,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
	},
	center: {
		textAlign: 'center',
	},

	/* product page */

	body: {
		backgroundColor: '#eeeeee',
		paddingTop: 30,
		paddingBottom: 30,
	},
	item: {
		backgroundColor: '#fff',
		padding: 25,
		margin: 15,
		paddingBottom: 40,
		position: 'relative',
		textAlign: 'center',
		marginBottom: 30,
		flex:1,
		alignItems: 'center',
		justifyContent: 'center',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 10},
  		shadowOpacity: 0.8,
		shadowRadius: 2,
		elevation: 6,
	},
	price: {
		fontWeight: 'bold',
		fontSize: 18,
		marginBottom: 15,
	},

	/* Topblock styles */

	topbar:{
		backgroundColor: '#f7f7f7',
		paddingTop:10,
		paddingBottom: 10,
		paddingLeft: 15,
		paddingRight:15,
		flexDirection: 'row',
		justifyContent:'space-between',
		alignItems:'center',
	},
	topleft:{
		flex:1,
		flexDirection: 'row',
	},
	toptext:{
		fontSize:15,
		fontWeight: '700',
		color:'#000',
	},
	toprightblock:{
		flex:1,
		alignItems:'flex-end',
		justifyContent:'flex-end',
	},
	signin:{
		fontSize:15,
		fontWeight: '700',
		color:'#f62f5e',
		marginLeft: 10,
	},
	cart_block:{
		position:'relative',
		right: 5,
	},
	cartcount:{
		color:'#fff',
		backgroundColor:'#f62f5e',
		position:'absolute',
		top:-15,
		width:25,
		height:25,
		textAlign: 'center',
		lineHeight: 25,
		borderRadius: 20,
	},

	/* Login page css */
	login_block_main:{
		padding:15,
		marginTop:15,
		marginBottom:30,
	},
	input_block:{
		marginTop:15,
	},
	input_text:{
		color:'#000',
		fontSize:14,
		fontWeight: '400',
		marginBottom:10,
	},
	login_btn_block:{
		flex:1,
		alignItems: 'flex-start',
		justifyContent: 'flex-start',
		flexDirection: 'row',
		marginTop:25,
	},
	loggedin_text:{
		fontSize:24,
		fontWeight:'500',
		textAlign:'center',
		color:'#000',
	},
	no_items_block:{
		paddingTop: 25,
		paddingBottom:25,
	},
	back_to_shop_btn:{
		flex:1,
		alignItems:'center',
		justifyContent:'center',
		marginTop:25,
	},

	social_media:{
		flex:1,
		justifyContent:'space-between',
		alignItems:'center',
		flexDirection:'row',
	},
	sm_btns:{
		marginBottom:15,
		textTransform:'capitalize',
	},

	/* Cart page css */

	cart_page_wraper:{
		padding: 15,
	},
  cart_header:{
    paddingLeft:15,
    paddingRight:15,   
	},
	cart_top_block:{
		backgroundColor: '#fff',
		paddingTop:20,
		paddingBottom:20,
		paddingLeft:15,
		paddingRight:15,
	},
	ptitle:{
		marginBottom:30,
	},
	cart_single_block:{
		flex:1,
		flexDirection:'row',
		justifyContent:'space-between',
		flexWrap:'wrap',
		textAlign: 'left',
		alignItems:'center',
		marginBottom: 15,
	},
	product_img:{
		padding:10,
		borderWidth:1,
		borderColor:'#b4b4b4',
		marginRight:15,
	},
	img_right_block:{
		flex:1,
		flexDirection:'column',
		flexWrap:'wrap',
		justifyContent:'flex-start',
		alignItems:'flex-start',
	},
	product_name:{
		fontSize:18,
		fontWeight: '700',
		color:'#2e2e2e',
		marginBottom: 15,
	},
	product_id:{
		fontSize:16,
		fontWeight: '400',
		color:'#2e2e2e',
		marginBottom: 15,
	},
	product_remove:{
		fontSize:16,
		fontWeight: '400',
		color:'#f62f5e',
	},
	product_size:{
		color: '#b4b4b4',
		fontWeight: '700',
		fontSize: 14,
	},
	numberof_products:{
		flex:1,
		flexDirection: 'row',
		alignItems:'center',
		justifyContent:'center',
		width: 150,
	},
	product_price:{
		fontSize: 22,
		fontWeight: '700',
		color: '#2e2e2e',
	},
	noof_items:{
		paddingLeft: 10,
		paddingRight: 10,
		color: '#2e2e2e',
		fontSize: 20,
		fontWeight: '700',
	},
	cart_bottom_block:{
		backgroundColor:'#efefef',
		paddingTop:20,
		paddingBottom:20,
		paddingLeft:15,
		paddingRight:15,
		marginBottom: 20,
		flex:1,
		flexDirection:'row',
		justifyContent:'space-between',
	},
	cart_size_block:{
		flex:1,
		justifyContent:'space-between',
		flexDirection:'row',
		alignItems:'center',
		marginTop: 15,
		marginBottom:30,
	},
	quantity:{
		backgroundColor:'#efefef',
	   color:'#2e2e2e',
		fontSize: 18,
		fontWeight: '700',
		borderRadius: 20,
		width:30,
		height:30,
		textAlign: 'center',
		lineHeight: 30,
	},

	/* Address block css */

	add_address_block:{
		padding:20,
		paddingBottom:50,
		backgroundColor:'#fff',
	},
	address_top_block:{
		flex:1,
		alignItems:'center',
		justifyContent:'space-between',
		flexDirection:'row',
		paddingBottom:15,
	},
	address_title:{
		fontSize:24,
		fontWeight:'500',
	},
	close:{
		fontSize:28,
		fontWeight:'700',
		color:'#000',
		opacity:0.5,
	},
	input_field:{
		backgroundColor:'#fff',
		borderColor:'#ced4da',
		borderWidth:1,
		borderStyle:'solid',
		height:40,
		borderRadius:10,
		paddingLeft:10,
		paddingRight:10,
	},
	select_field:{
		backgroundColor:'#fff',
		borderColor:'#ced4da',
		borderWidth:10,
		borderStyle:'solid',
		height:40,
		borderRadius:10,
		paddingLeft:10,
		paddingRight:10,
	},
	space_bot:{
		paddingBottom:50,
	},
	space_top:{
		marginTop:15,
	},

	/* Delivery Page css */

	back_and_next_btn_block:{
		flex:1,
		alignItems:'center',
		justifyContent:'space-between',
		flexDirection:'row',
	},
	delivery_block:{
		padding:15,
	},

	/* Confirmation page css */

	confirmation_block:{
		margin: 15,
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
	},
	ordertxt:{
		fontWeight:'normal',
		fontSize:16,
		textAlign:'left',
		color:'#000',
		marginTop:15,
		flex:1,
		alignItems:'center',
		justifyContent:'center',
		flexDirection:'row',
	},
	headtxt:{
		fontWeight:'bold',
		fontSize:16,
		textAlign:'left',
		color:'#000',
	},
	success_block:{
		margin: 15,
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
		textAlign:'center',
		flex:1,
		alignItems:'center',
		justifyContent:'center',
	},
	success_txt:{
		fontSize:18,
		fontWeight:'normal',
		color:'#000',
		textAlign: 'center',
		marginBottom:15,
	},
	addaddress_block:{
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
		textAlign:'center',
		flex:1,
		alignItems:'center',
		justifyContent:'center',
		flexDirection:'column',
	},
	address_block:{
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
		flex:1,
		alignItems:'flex-start',
		justifyContent:'flex-start',
		flexDirection:'column',
	},
	nospace:{
		margin:0,
		padding:0,
	},
	plus:{
		fontSize:100,
		fontWeight:'600',
		color:'#6c6c6c',
		opacity:0.5,
	},
	center_position:{
		flex:1,
		alignItems:'center',
		justifyContent:'center',
	},
	delivery_options:{
		flex:1,
		alignItems:'flex-start',
		justifyContent:'space-between',
		flexDirection:'row',
	},
	radio_btn:{
		flex:1,
		alignItems:'flex-start',
		justifyContent:'flex-start',
		flexDirection:'row',
	},
	options:{
		flex:1,
		alignItems:'flex-end',
		justifyContent:'flex-end',
		flexDirection:'row',
		marginTop:8,
		fontWeight:'700',
		color:'#000',
		fontSize:16,
	},
	mright:{
		marginRight:15,
	},
	selected:{
		borderColor:'#ff0000',
		borderWidth: 1,
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
		flex:1,
		alignItems:'flex-start',
		justifyContent:'flex-start',
		flexDirection:'column',
	},
	notselected:{
		marginBottom: 30,
		padding: 25,
		backgroundColor: '#fff',
		position: 'relative',
		shadowColor: '#000',
  		shadowOffset: {width: 0, height: 2},
  		shadowOpacity: 0.8,
  		shadowRadius: 2,
		elevation: 5,
		flex:1,
		alignItems:'flex-start',
		justifyContent:'flex-start',
		flexDirection:'column',
	},

	/* Search results css */

	search_icon:{
		marginRight:5,
		height:32,
		width:32,
	},
	search_main:{
		padding: 15,
		backgroundColor: '#f7f7f7',
		flex:1,
		alignItems:'flex-start',
		justifyContent:'space-between',
		flexDirection:'row',
	},
	search_input:{
		borderColor:'#6c6c6c',
		borderWidth:1,
		borderRadius:10,
		backgroundColor:'#fff',
		paddingTop:5,
		paddingBottom:5,
		paddingLeft:10,
		paddingRight:10,
		color:'#000',
		height:45,
		marginBottom: 10,
		width:'65%',
	},
	space:{
		padding:15,
	},
	search_results:{
		backgroundColor: '#f7f7f7',
	},
});
